version: '2'

services:
    app:
      image: nginx:latest
      ports:
        - "8088:80"
      volumes:
        - ./app:/var/www/html
        - ./docker/back/site.conf:/etc/nginx/conf.d/default.conf
      environment:
        - APP_ENV=development
        - APP_DEBUG=true

    php:
      build: docker/back
      volumes:
        - ./app:/var/www/html
        - ./docker/back/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

    db:
      image: mysql/mysql-server
      ports:
        - "3310:3306"
      volumes:
        - data-volume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: mysql4quiz
        MYSQL_USER: dev
        MYSQL_PASSWORD: mysql4quiz
        MYSQL_DATABASE: quiz

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8087:80

    front:
      image: nginx:latest
      ports:
        - "8089:80"
      volumes:
        - ./ng-quiz:/var/www/html
        - ./docker/front/site.conf:/etc/nginx/conf.d/default.conf

    node:
      image: node:latest
      
volumes:
  data-volume: