version: "3.7"
services:
  app:
    build:
      args:
        user: isef
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: isef
    container_name: isef-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - isef

  db:
    image: mysql/mysql-server
    container_name: isef-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql4quiz
      MYSQL_USER: dev
      MYSQL_PASSWORD: mysql4quiz
      MYSQL_DATABASE: quiz
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysqldata:/var/lib/mysql
    networks:
      - isef

  nginx:
    image: nginx:alpine
    container_name: isef-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/html
      - ./docker/back/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - isef

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: isef-pma
      restart: unless-stopped
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1      
      ports:
        - 8087:80
      networks:
      - isef

networks:
  isef:
    driver: bridge